### ISSUE TITLE
pentatonic box retuns the wrong box. 

### ISSUE THREAD

**Issue by Aduffy** [moonwave99/fretboard.js#11]
`var box  = pentatonic({ box: 1, root: 'A2', mode: 'minor' });`

creates 
![image](https://user-images.githubusercontent.com/265857/100527374-ce36ab00-3186-11eb-86dd-10d507f20d0b.png)

But Box 1 should be 

![image](https://user-images.githubusercontent.com/265857/100527383-e0b0e480-3186-11eb-80c9-e8755d3f284e.png)

to get that shape I need to request box 5 .. 

![image](https://user-images.githubusercontent.com/265857/100527394-00e0a380-3187-11eb-884e-374a34c66963.png)

**Comment by moonwave99** [comment]
I numbered the boxes starting from the first _major_ shape, i.e. the one related to the E-shaped box (root and second on the 6th string, 3rd and 5th on the 5th...).

Since "box 1" is the relative minor of the G shaped, you'll get it from box 5 ([see examples](https://moonwave99.github.io/fretboard.js/examples-boxes.html)).

One may argue that you learn minor pentatonic first, so box 1 should be the one you posted ^^ personally I find the numbering convention arbitrary and confusing (at least I found while learning), I would rather define the box on where the first root actually is.

**Comment by Aduffy** [comment]
although I do see your logic, there already is a standardized naming for each box that is common place as is seen on a google image search for "[box 1 minor pentatonic scale](https://www.google.com/search?q=box+1+minor+pentatonic+scale&safe=off&sxsrf=ALeKk03daGOgX1hUnCypoAb1g3_Cv1YQ2Q:1606670527766&source=lnms&tbm=isch&sa=X
)" 
If a guitar teacher where to ask a student to play "Box 1 of A Minor Penatonic" , the shape they would expect to see is as per my example...

**Comment by moonwave99** [comment]
Since students are not looking at this source code :D, you can make your own wrapper - [see example](https://codepen.io/moonwave99/pen/gOwbdEx):

```js
import { pentatonic } from '@moonwave99/fretboard.js';

function minorPentatonic({ box, root }) {
  return pentatonic({
    box: box === 1 ? 5 : box - 1,
    root,
    mode: 'minor'
  });
}
```

All in all, it may make sense to allow `const { major, minor } = pentatonic`, allowing for more exotic pentatonic flavours like Japanese ryukyu, etc. in the future.

**Comment by Aduffy** [comment]
Ah.. not so :-) I am a student looking to try to be my own teacher with the help of this and a few other tool :-P 

But the wrapper works for me. Cheers.

**Comment by moonwave99** [comment]
Should be fine in v0.2.

**Comment by Aduffy** [comment]
Are you renaming the boxes as per my suggestion?? As I am using that custom minorPentatonic function currently to offset them for my use.

**Comment by moonwave99** [comment]
[Yes ^^](https://moonwave99.github.io/fretboard.js/examples-systems.html)

<img width="1143" alt="Screenshot 2020-12-22 at 23 06 34" src="https://user-images.githubusercontent.com/380184/102937408-5c623080-44aa-11eb-9fac-45aed0fad530.png">
